version: 0.2

phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
  pre_build:
    commands:
      - echo Nothing on prebuild steps
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Starting test
      - npm run test:all
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
